## Decompositions
Here are some decompositions

[Source](https://people.duke.edu/~ccc14/sta-663-2016/07_LinearAlgebra2.html#LU-Decomposition-and-Gaussian-Elimination)

### LU Decomposition
A = P * L * U

P - permutation matrix

L - lower triangle

U - upper triangle

In [21]:
import pprint
import numpy as np

mat_a = np.array([[1,3,4],[2,1,3],[4,1,2]])
print('A:')
pprint.pprint(mat_a)

# upper & lower triangle, D is diagonal, but no pivoting.
U = np.triu(mat_a,1)
L = np.tril(mat_a, -1)
D = np.tril(np.triu(mat_a))
print(L)
print('-' * 80)
print(D)
print('-' * 80)
print(U)
print(L @ D @ U) # This is totally wrong.

A:
array([[1, 3, 4],
       [2, 1, 3],
       [4, 1, 2]])
[[0 0 0]
 [2 0 0]
 [4 1 0]]
--------------------------------------------------------------------------------
[[1 0 0]
 [0 1 0]
 [0 0 2]]
--------------------------------------------------------------------------------
[[0 3 4]
 [0 0 3]
 [0 0 0]]
[[ 0  0  0]
 [ 0  6  8]
 [ 0 12 19]]


In [22]:
import scipy.linalg as la

# Since numpy uses partial pivoting, P is the permutation matrix
P, L, U = la.lu(mat_a)
print("P:")
pprint.pprint(P)
print("L:")
pprint.pprint(L)
print("U:")
pprint.pprint(U)
print('P*L*U:')
pprint.pprint(P @ L @ U) # we should back to A = P * L * U

P:
array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.25      , 1.        , 0.        ],
       [0.5       , 0.18181818, 1.        ]])
U:
array([[4.        , 1.        , 2.        ],
       [0.        , 2.75      , 3.5       ],
       [0.        , 0.        , 1.36363636]])
P*L*U:
array([[1., 3., 4.],
       [2., 1., 3.],
       [4., 1., 2.]])


### LDU Decomposition
A = P * L * D * U

D - diagonal

In [23]:
P, L, U = la.lu(mat_a)
# L's diagonal has 1's
D = np.diag(np.diag(U))

U /= np.diag(U)[:, None]
# now U's diagonal has 1's

print("P:")
pprint.pprint(P)
print("L:")
pprint.pprint(L)
print("D:")
pprint.pprint(D)
print("U:")
pprint.pprint(U)
print('P*L*D*U:')
pprint.pprint(P @ L @ D @ U)


P:
array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.25      , 1.        , 0.        ],
       [0.5       , 0.18181818, 1.        ]])
D:
array([[4.        , 0.        , 0.        ],
       [0.        , 2.75      , 0.        ],
       [0.        , 0.        , 1.36363636]])
U:
array([[1.        , 0.25      , 0.5       ],
       [0.        , 1.        , 1.27272727],
       [0.        , 0.        , 1.        ]])
P*L*D*U:
array([[1., 3., 4.],
       [2., 1., 3.],
       [4., 1., 2.]])


### Jordan Normal Forms
Jordan decomposition is not stable numerically.
But in theory, it's important.

In [ ]:
from sympy import Matrix

a = np.array([[5, 4, 2, 1], [0, 1, -1, -1], [-1, -1, 3, 0], [1, 1, -1, 2]])
print(np.linalg.matrix_rank(a))
m = Matrix(a)
P, J = m.jordan_form()


### Rank Factorization


### SVD - Singular Value Decomposition
[machinelearningmastery.com](https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/)
has a good discussion.
[Here](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.8-Singular-Value-Decomposition/)
[Here](https://www.askpython.com/python/examples/singular-value-decomposition)

A = np.array([[3,4,3],[1,2,3],[4,2,1]])

U, D, VT = np.linalg.svd(A)

A_remake = (U @ np.diag(D) @ VT)

### QR Decomposition

### Eigenvalues and Eigenvectors

### Generalized Inverse
For n X m matrix, there is no inverse. However,
https://meshlogic.github.io/posts/jupyter/linear-algebra/linear-algebra-numpy-2/

### Cholesky decomposition
A = U<sup>*</sup> U, where * means conjugate transpose.

https://en.wikipedia.org/wiki/Cholesky_decomposition

### Schur decomposition