## Vectors

In [22]:
import numpy

vec_a = numpy.array([1, 2, 3])
x = 5.0
print(x * vec_a) # vector times scalar
print(vec_a.T) # vector and matrix operations - transpose
print(vec_a.shape)
vec_a1 = vec_a.reshape(3, 1) # change 1 row X 3 cols to 3 rows X 1 col
print(vec_a1)
print(vec_a1.shape)
print(vec_a.reshape(-1, 1)) # specify one dimension is enough

vec_b = numpy.array([2, 3, 4])
print(vec_a.dot(vec_b)) # inner product, but check doc for different dimensions
# https://numpy.org/doc/stable/reference/generated/numpy.dot.html
# There is also vdot: https://numpy.org/doc/stable/reference/generated/numpy.vdot.html

[ 5. 10. 15.]
20


## Matrices

In [23]:
mat_a = numpy.array([[1, 2], [3, 4]])

print(numpy.linalg.det(mat_a))
print(numpy.linalg.inv(mat_a)) # only square matrix has inv
print(numpy.zeros(3, 2)) # a 3 X 2 matrix with all zero values
print(numpy.ones(3, 2)) # a 3 X 2 matrix with all values 1
print(numpy.random.rand(3, 2)) # random numbers between 0 and 1
print(numpy.random.randn(3, 2)) # random numbers with normal distribution

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


scalar * matrix

In [24]:
print(x * mat_a)

[[ 5. 10.]
 [15. 20.]]


vector * matrix

In [25]:
vec_c = numpy.array([5, 6])
print(mat_a.dot(vec_c)) # this is actually matrix * vector
# don't do mat_a * vec_c, it's element wise.
print(mat_a * vec_c)
# another correct way
print(mat_a @ vec_c)


[17 39]
[[ 5 12]
 [15 24]]
[17 39]


matrix * matrix

In [26]:
mat_b = numpy.array([[5, 6, 7], [8, 9, 10]])
# This is not in math, not working at all
# print(mat_a * mat_b)
# This is in math
print(mat_a @ mat_b)


[[21 24 27]
 [47 54 61]]


Linear equations

In [ ]:
print(numpy.linalg.solve(mat_a, vec_c))
# actually, we could find inverse of mat_a, then times that to vec_c
# Matrix A is singular if there exists x != 0 such that Ax = 0.
# det(A) = 0

# Hilbert Matrix
# https://blogs.mathworks.com/cleve/2017/07/17/what-is-the-condition-number-of-a-matrix/
B = [[4.1, 2.8], [9.7, 6.6]]
print(numpy.linalg.det(B)) # close to 0
print(numpy.linalg.cond(B)) # >> 1